In [2]:
import pandas as pd
from prepix.quality import column_summary, missing_report, duplicate_report

In [5]:
df_missing = pd.DataFrame({
    "Name": ["Aman", "Rahul", None, "Neha", "Vikas"],
    "Age": [21, None, 20, 23, None],
    "Marks": [85, 76, None, 68, 85],
    "City": ["Indore", "Bhopal", "Indore", None, "Bhopal"]
})

df_missing

    Name   Age  Marks    City
0   Aman  21.0   85.0  Indore
1  Rahul   NaN   76.0  Bhopal
2    NaN  20.0    NaN  Indore
3   Neha  23.0   68.0     NaN
4  Vikas   NaN   85.0  Bhopal

In [6]:
df_normal = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Priya", "Neha", "Vikas"],
    "Age": [21, 22, 20, 23, 21],
    "Marks": [85, 76, 91, 68, 85],
    "City": ["Indore", "Bhopal", "Indore", "Delhi", "Bhopal"]
})

df_normal

    Name  Age  Marks    City
0   Aman   21     85  Indore
1  Rahul   22     76  Bhopal
2  Priya   20     91  Indore
3   Neha   23     68   Delhi
4  Vikas   21     85  Bhopal

In [8]:
df_duplicate = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Priya", "Aman", "Rahul"],
    "Age": [21, 22, 20, 21, 22],
    "Marks": [85, 76, 91, 85, 76],
    "City": ["Indore", "Bhopal", "Indore", "Indore", "Bhopal"]
})

df_duplicate

    Name  Age  Marks    City
0   Aman   21     85  Indore
1  Rahul   22     76  Bhopal
2  Priya   20     91  Indore
3   Aman   21     85  Indore
4  Rahul   22     76  Bhopal

In [9]:
result = column_summary(df_normal)
result

,Column,Data Type,Missing Values,Missing Percentage(%),Unique Values,Memory(Bytes),Suggested Type
0,Name,str,0,0.0,5,308,Categorical
1,Age,int64,0,0.0,4,40,Numeric
2,Marks,int64,0,0.0,4,40,Numeric
3,City,str,0,0.0,3,314,Categorical

In [10]:
df_copy = df_normal.copy()

In [11]:
column_summary(df_normal)

,Column,Data Type,Missing Values,Missing Percentage(%),Unique Values,Memory(Bytes),Suggested Type
0,Name,str,0,0.0,5,308,Categorical
1,Age,int64,0,0.0,4,40,Numeric
2,Marks,int64,0,0.0,4,40,Numeric
3,City,str,0,0.0,3,314,Categorical

In [12]:
df_normal.equals(df_copy)

True

In [13]:
column_summary(df_missing)

,Column,Data Type,Missing Values,Missing Percentage(%),Unique Values,Memory(Bytes),Suggested Type
0,Name,str,1,20.0,4,278,Categorical
1,Age,float64,2,40.0,3,40,Numeric
2,Marks,float64,1,20.0,3,40,Numeric
3,City,str,1,20.0,2,284,Categorical (2 values)

In [14]:
df_wide = pd.DataFrame({
    f"Column_{i}": range(100)
    for i in range(150)
})

print(df_wide.shape)

(100, 150)

In [15]:
result = column_summary(df_wide)

print(result.shape)
result.head()

(150, 7)

,Column,Data Type,Missing Values,Missing Percentage(%),Unique Values,Memory(Bytes),Suggested Type
0,Column_0,int64,0,0.0,100,800,Numeric
1,Column_1,int64,0,0.0,100,800,Numeric
2,Column_2,int64,0,0.0,100,800,Numeric
3,Column_3,int64,0,0.0,100,800,Numeric
4,Column_4,int64,0,0.0,100,800,Numeric